# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore  ./src/dotnet-demoapp.csproj
    - name: Build
      run: dotnet build --no-restore ./src/dotnet-demoapp.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/dotnet-demoapp.csproj
    
    - name: Package the application
      run: dotnet pack --configuration Release --output ./nuget-packages ./src/dotnet-demoapp.csproj

    - name: Push NuGet package to Nexus
      run: dotnet nuget push ./nuget-packages/*.nupkg --source "Nexus" --api-key ${{ secrets.NEXUS_API_KEY }}
      env:
        NUGET_REPOSITORY_URL: "http://3.111.23.62:8081/repository/nuget-group/"
      continue-on-error: false
