# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net


name: .NET

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore  ./src/dotnet-demoapp.csproj
    - name: Build
      run: dotnet build --no-restore ./src/dotnet-demoapp.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./src/dotnet-demoapp.csproj
      
    - name: verify the Nuget version
      run: dotnet nuget --version
      
    - name: Package the application
      run: dotnet pack --configuration Release --output ./nuget-packages ./src/dotnet-demoapp.csproj

    - name: Configure NuGet for Nexus
      run: |
        dotnet nuget add source "http://3.111.23.62:8081/repository/nuget-hosted/" \
          --name "Nexus" \
          --username "${{ secrets.NEXUS_USERNAME }}" \
          --password "${{ secrets.NEXUS_PASSWORD }}" \
          --store-password-in-clear-text

    - name: Push NuGet package to Nexus
      run: dotnet nuget push ./nuget-packages/*.nupkg --source "http://3.111.23.62:8081/repository/nuget-hosted/" --api-key ${{ secrets.NEXUS_API_KEY }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Docker Image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        working-directory: ./src

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/dotnet-demoapp:${{ github.sha }}

    - name: Cleanup Docker Images
      run: |
        docker rmi ${{ secrets.ECR_REGISTRY }}/dotnet-demoapp:${{ github.sha }}

